### ISSUE TITLE
Documentation page is broken

### ISSUE THREAD

**Issue by PhyberApex** [joukevandermaas/saule#248]
Hey we just noticed the link to your documentation is leading to a broken page. Any chance on fixing that?

~Cheers

**Comment by joukevandermaas** [comment]
I think I fixed it.. it works for me now but it might take a second for you because of DNS caching.

**Comment by PhyberApex** [comment]
SOrry for being a PITA but it still does not work on my end :/

**Comment by joukevandermaas** [comment]
It seems to be some weird caching issue or something. When I click to it from the github configuration page it works, but when I click from the repo front page it does not. I changed the URL now from http to https and that fixed it for me, maybe you too?

**Comment by PhyberApex** [comment]
Yeah you are right. I just checked and it does still not work on my PC. I did check however from another device and there it worked fine...so I think this will fix itself after the cache runs out....weird. Thanks a ton!
